#!/bin/bash

hasad="N";
hasod="N";
pingdir=`ping -c 1 mica.edu`
if [[ $pingdir != "ping: cannot resolve mica.edu: Unknown host" ]];
then
        id itunesu > /dev/null 2>&1
        if [[ $? -eq 0 ]]; then
                hasad="Y";
        fi

        id diradmin > /dev/null 2>&1
        if [[ $? -eq 0 ]]; then
                hasod="Y";
        fi

        if [[ $hasad != "Y" ]] || [[ $hasod != "Y" ]]; then
                echo "O:${hasod} A:${hasad}";
                d=`date`;
                echo $d;
        else
                echo "OK";
        fi
fi
