#!/bin/bash

osvers=$(sw_vers -productVersion | awk -F. '{print $2}')

if [[ ${osvers} -lt 7 ]]; then
echo "Not Available"
fi
if [[ ${osvers} -gt 12 ]]; then
echo "Future Not Known Yet. Revise Me"
fi

# Checks Gatekeeper status on 10.7.x to Current(?) Macs

if [[ ${osvers} -ge 7 && ${osvers} -le 12 ]]; then
gatekeeper_status=`spctl --status | grep "assessments" | cut -c13-`
if [ $gatekeeper_status = "disabled" ]; then
result=Disabled
else
result=Active
fi
echo $result
fi
